### PR TITLE
Implemented Select Command

### PR DESCRIPTION
**Pull request by Alvinnyk**
- [x] Logic: Implemented Select command to view details of a timeslot #214 

- [x] Logic: Added checker for addevent command out of range timeslots #211 

- [x] Logic: Show command can now take in empty arguments to show user's schedule

- [x] Updated UI: Improved Popup for select command

- [x] Updated UI: Implemented different colours for different events

- [x] Updated UI: Changed welcome message to welcome the user instead

- [x] Updated UI: Timeslots now shows ID of the timeslot to facilitate Select command

### CODE REVIEW

**Review by YiJiee — CHANGES_REQUESTED** [review]
Can you revert back the changes u made for my class? I'll handle the hiding of text in group schedule. I wrote my test cases for ScheduleView already so it'll stop working if i use your version...

**Comment by Alvinnyk** [comment]
Moved color generation to display model.
Added state tracking for popup command.

**Review by klementtan — APPROVED** [review]
Nice! LGTM

**Review by YiJiee — APPROVED** [review]
Approved.

**Pull request merged**
